// <auto-generated />
namespace MVCBiblioteka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lends : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lends));
        
        string IMigrationMetadata.Id
        {
            get { return "201612072132114_lends"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
